#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -V
#$ -j y
#$ -pe mpi_16_tasks_per_node 16
#$ -M czeyuan@bu.edu

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

module load samtools/0.1.19 bowtie2 boost tophat

tophat --no-novel-juncs -G /project/bf528/project_2/reference/annot/mm9.gtf --segment-length=20 --segment-mismatches=1 -r 200 -p 16 -o P0_1_tophat /project/bf528/project_2/reference/mm9 /projectnb/bf528/users/group_8/project_2/data/P0_1_1.fastq  /projectnb/bf528/users/group_8/project_2/data/P0_1_2.fastq

echo "Job finished: $(date +%F)"
